---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-production
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-organization-reference-nestjs
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-organization-reference-nestjs
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-organization-reference-nestjs
          image: asia.gcr.io/uii-cloud-project/hcm/backend/svc-organization-reference-nestjs:prod
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: GCLOUD_PROJECT
              value: "faq-1614588549731"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/usr/src/app/service_account_credentials.json"
          ports:
            - name: http-api
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-production
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-organization-reference-nestjs-mapping
      prefix: /v1/organization-reference
      rewrite: /public/api/v1
      service: svc-organization-reference-nestjs.hcm-production
      timeout_ms: 30000
spec:
  selector:
    svc: svc-organization-reference-nestjs
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  name: svc-organization-reference-nestjs
  namespace: hcm-production
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: svc-organization-reference-nestjs
  targetCPUUtilizationPercentage: 50
