---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-production
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-organization-reference-nestjs
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-organization-reference-nestjs
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-organization-reference-nestjs
          image: asia.gcr.io/uii-cloud-project/hcm/backend/svc-organization-reference-nestjs:prod
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "80"
            - name: DATABASE_HOST
              value: "dbproduction.bsi.io"
            - name: DATABASE_PORT
              value: "6033"
            - name: DATABASE_USER
              value: "hcmorganisasi_app"
            - name: DATABASE_PASSWORD
              value: "m6S7rnkw623XVyWrjTH8"
            - name: DATABASE_DB
              value: "hcm_organisasi"
            - name: MINIO_ACCESSKEY
              value: "AjeBhr2B5WUFFmPS9FYf"
            - name: MINIO_SECRETKEY
              value: "M3432ax42q377V39qGQ3Dp9N4R2w5452efY876wd"
            - name: MINIO_ENDPOINT
              value: "s3.uii.ac.id"
          ports:
            - name: http-api
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-production
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-organization-reference-nestjs-mapping
      prefix: /v1/organization-reference
      rewrite: /public/api/v1
      service: svc-organization-reference-nestjs.hcm-production
      timeout_ms: 30000
spec:
  selector:
    svc: svc-organization-reference-nestjs
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  name: svc-organization-reference-nestjs
  namespace: hcm-production
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: svc-organization-reference-nestjs
  targetCPUUtilizationPercentage: 50
