---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-organization-reference-nestjs
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-organization-reference-nestjs
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-organization-reference-nestjs
          image: asia.gcr.io/uii-cloud-project/hcm/backend/svc-organization-reference-nestjs:stag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
            - name: NODE_ENV
              value: "staging"
            - name: PORT
              value: "80"
            - name: DATABASE_HOST
              value: "dbstaging.bsi.io"
            - name: DATABASE_PORT
              value: "6033"
            - name: DATABASE_USER
              value: "sholichin"
            - name: DATABASE_PASSWORD
              value: "bismillahstaging123"
            - name: DATABASE_DB
              value: "hcm_organisasi"
            - name: AWS_ACCESS_KEY_ID
              value: "2m8mYMxUUTwTwCqPgy2F"
            - name: AWS_SECRET_ACCESS_KEY
              value: "6yxf3LPgy4kMNLpKAACe9PzzeS5mJU8cKWA5PwVu"
            - name: AWS_ENDPOINT
              value: "https://s3-staging.uii.ac.id"
            - name: AWS_ENDPOINT_UPLOAD
              value: "https://s3-staging.uii.ac.id"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_VERSION
              value: "latest"
          ports:
            - name: http-api
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-organization-reference-nestjs
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  namespace: hcm-stag
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-organization-reference-nestjs-mapping
      prefix: /v1/organization-reference
      rewrite: /public/api/v1
      service: svc-organization-reference-nestjs.hcm-stag
      timeout_ms: 30000
spec:
  selector:
    svc: svc-organization-reference-nestjs
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    svc: svc-organization-reference-nestjs
    tier: backend
  name: svc-organization-reference-nestjs
  namespace: hcm-stag
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: svc-organization-reference-nestjs
  targetCPUUtilizationPercentage: 50
